### ISSUE TITLE
除movielens、IFM、Amazon外其他数据集KG构建

### ISSUE THREAD

**Issue by happy-xty** [RUCAIBox/RecSysDatasets#102]
请问除movielens、IFM、Amazon外，其他数据集应该怎么构建KG呀？

**Comment by Sherry-XLL** [comment]
@happy-xty 您好，基于知识图谱的推荐系统获取数据集的常用方法主要有以下三种：
- Item attribute graph 直接根据商品的属性信息构造伪知识图谱
  - eg：Yelp（category, location, and attribute）
- Internal knowledge graph 企业内部数据
  - eg：微软 Satori (CKE, DKN, RippleNet, KGNN-LS)，美团大脑 (Dianping-Food)
- Item-to-entity linkage to external 根据物品属性信息链接到外部知识图谱
 
RecBole 采用的方式是第三种，所提供的知识图谱是基于 KB4Rec 中的方法，可以参考 KB4Rec 的[论文](https://doi.org/10.1162/dint_a_00008)和 [repo](https://github.com/RUCDM/KB4Rec)。

也就是说，对于其他推荐系统数据集，要想构造对应的知识图谱，首先需要取得推荐系统物品和知识图谱实体之间的映射链接。为了获取链接关系，可以将推荐系统平台收集的名称、类型、作者、年份等商品信息用作上下文特征。比如直接匹配商品名和知识图谱中的名称（YAGO），或者利用 Google 和 wikidata 提供的 API 接口，以商品名为 query，匹配外部 KG 中的 entity id。

常用的 API 接口有以下三种：
- [Google Knowledge Graph API](https://kgsearch.googleapis.com/v1/entities:search](https://kgsearch.googleapis.com/v1/entities:search?query=Fudan&key=)：返回 Freebase id 以及类型、描述等辅助信息
- [Freebase](https://www.googleapis.com/freebase/v1/search](https://www.googleapis.com/freebase/v1/search?query=fudan&format=entity)：仅返回 Freebase id 以及名称，直接获取的搜索结果可利用信息少
- [Wikidata](https://www.wikidata.org/w/api.php)：仅返回 Wikidata id 以及名称，直接获取的搜索结果可利用信息少

感谢您对 [RecSysDatasets](https://github.com/RUCAIBox/RecSysDatasets) 的关注，在构造知识图谱的过程中有什么问题欢迎随时交流。

**Comment by happy-xty** [comment]
@Sherry-XLL 好哒，谢谢！
