### ISSUE TITLE
关于gowalla数据的run_duplicate_removal，可能有代码错误

### ISSUE THREAD

**Issue by DJDONGx** [RUCAIBox/RecSysDatasets#105]
你好，https://github.com/RUCAIBox/RecSysDatasets/blob/3a27f94fc2b3901ee9391baed6b26a3a65ded6fd/conversion_tools/src/extended_dataset.py#L917
这一个循环最后是否应该添加一行 cnt_row +=1
如果不添加的话，最后一个user就只有最后一个item被写入all_user

**Comment by Sherry-XLL** [comment]
@DJDONGx 感谢您的反馈，此处不更新行数确实会有问题，我们已修正这一bug。

https://github.com/RUCAIBox/RecSysDatasets/blob/43d4ca06e189d4880383a0c01e2d6343ba95f901/conversion_tools/src/extended_dataset.py#L918-L919

**Comment by DJDONGx** [comment]
谢谢
