### ISSUE TITLE
知识图谱数据集问题

### ISSUE THREAD

**Issue by KlaineWei** [RUCAIBox/RecSysDatasets#106]
能否提供下将数据集转换成kg文件的脚本？现在只提供了ml，amazonbooks和lfm的已经处理好的kg文件，但是缺少其他数据集

**Comment by Sherry-XLL** [comment]
@KlaineWei 您好，要获取知识图谱数据集首先需要将物品的 ID 和知识图谱的实体 ID 相对应，RecSysDatasets 中提供的三个知识图谱数据集都是基于 [KB4Rec](https://github.com/RUCDM/KB4Rec) 的实体链接工作，由于没有其他开源的知识图谱 ID 链接文件，所以无法直接获得其他数据集的知识图谱数据。

**Comment by yunshanlucky** [comment]
> @KlaineWei 您好，要获取知识图谱数据集首先需要将物品的 ID 和知识图谱的实体 ID 相对应，RecSysDatasets 中提供的三个知识图谱数据集都是基于 [KB4Rec](https://github.com/RUCDM/KB4Rec) 的实体链接工作，由于没有其他开源的知识图谱 ID 链接文件，所以无法直接获得其他数据集的知识图谱数据。

请问如果自己想通过KB4Rec构造recbole的是数据集，难度大嘛，有没有现成的资料可以学习使用，谢谢

**Comment by KlaineWei** [comment]
@yunshanlucky conversion tools里有KG三个数据集的生成代码，可以进行参考

**Comment by yunshanlucky** [comment]
@KlaineWei 感谢您的回答，可能由于我基础有限，只能使用官方转换好的3个KG数据集，如果我需要进一步将yelp2018或者last fm数据集转化为KG形式，我需要怎么进行下一步操作，由于网络中学习资源匮乏，能否提供相应的学习资料，或者是详细的数据集转化方法，您的回答对我帮助非常大，再次非常感谢您的回答
