### ISSUE TITLE
Problem of KG Dataset 

### ISSUE THREAD

**Issue by HUE96yhz** [RUCAIBox/RecSysDatasets#93]
@ShanleiMu I have seen that in the paper of KGAT: “To ensure the KG quality, we then preprocess the three KG parts by filtering out infrequent entities (i.e., lowever than 10 in both datasets) and retaining the relations appearing in at least 50 triplets.”
Whether the knowledge graph dataset in the `RecsysDataSets` also has related processing operations？
Is there any additional processing for the knowledge graph dataset (.kg file) built using `conversion_tools `in the `RecsysDataset` project?Or just follow the `KB4Rec` project

**Comment by ShanleiMu** [comment]
No, the script file in `RecsysDataSets` is only used to link rec data to kg data and extract corresponding kg entities, filtering operations are not included.

Sorry, this repo currently does not support such processing scripts.
You can first obtain `*.kg` and `*.link` by using `conversion_tools` provided by `RecsysDatasets` , and then write extra simple processing scripts to accomplish what you want.
